name: 'test'
on: ['push']
jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/setup-go@v1'
        with: {go-version: '1.15'}
      - name: 'Install golangci-lint'
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b "${HOME}/bin" v1.23.8
          echo "::add-path::${HOME}/bin"
      - uses: 'actions/checkout@v1'
      - name: 'Test'
        run: 'make test'
